try:
    import test
except Exception as e:
    print(e)
except:
    print("error")
